name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Deploy the site
        uses: jpopelka/hugo-deploy-gh-pages
        env:
          HUGO_VERSION: 0.110.0
          TARGET_REPO: kraegpoeth/kraegpoeth.github.io
          TARGET_BRANCH: master
          TOKEN: ${{ secrets.GH_TOKEN }}
          CNAME: kraegpoeth.github.io
